package dev.abelab.daas.db.entity;

public class Dajare {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dajare.id
     *
     * @mbg.generated Sat May 15 23:27:17 JST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dajare.text
     *
     * @mbg.generated Sat May 15 23:27:17 JST 2021
     */
    private String text;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dajare.id
     *
     * @return the value of dajare.id
     *
     * @mbg.generated Sat May 15 23:27:17 JST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dajare.id
     *
     * @param id the value for dajare.id
     *
     * @mbg.generated Sat May 15 23:27:17 JST 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dajare.text
     *
     * @return the value of dajare.text
     *
     * @mbg.generated Sat May 15 23:27:17 JST 2021
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dajare.text
     *
     * @param text the value for dajare.text
     *
     * @mbg.generated Sat May 15 23:27:17 JST 2021
     */
    public void setText(String text) {
        this.text = text;
    }
}