package dev.abelab.daas.db.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Dajare {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dajare.id
     *
     * @mbg.generated Sun May 16 15:10:30 JST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dajare.text
     *
     * @mbg.generated Sun May 16 15:10:30 JST 2021
     */
    private String text;
}