package dev.abelab.daas.db.entity;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Dajare {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dajare.id
     *
     * @mbg.generated Tue May 18 11:12:38 JST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dajare.text
     *
     * @mbg.generated Tue May 18 11:12:38 JST 2021
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dajare.score
     *
     * @mbg.generated Tue May 18 11:12:38 JST 2021
     */
    private Double score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dajare.reading
     *
     * @mbg.generated Tue May 18 11:12:38 JST 2021
     */
    private String reading;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dajare.created_at
     *
     * @mbg.generated Tue May 18 11:12:38 JST 2021
     */
    private Date createdAt;
}