version: "3"
services:
  db-local:
    build: ./mysql
    restart: always
    environment:
      MYSQL_DATABASE: "daas"
      MYSQL_USER: "daas"
      MYSQL_PASSWORD: "daas"
      MYSQL_ROOT_PASSWORD: "daas"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/log/local:/var/log/mysql
  db-test:
    build: ./mysql
    restart: always
    environment:
      MYSQL_DATABASE: "daas"
      MYSQL_USER: "daas"
      MYSQL_PASSWORD: "daas"
      MYSQL_ROOT_PASSWORD: "daas"
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/log/test:/var/log/mysql
