spring:
  datasource:
    url: jdbc:mysql://localhost:3306/daas
    username: "daas"
    password: "daas"
    driver-class-name: com.mysql.jdbc.Driver

  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.user}
    password: ${spring.datasource.password}
    locations: classpath:db/migration
    driver-class-name: ${spring.datasource.driver-class-name}
