spring:
  datasource:
    url: jdbc:mysql://localhost:3306/daas
    username: "daas"
    password: "daas"
    driver-class-name: com.mysql.jdbc.Driver

  flyway:
    password: "daas"
    user: "daas"
    url: jdbc:mysql://localhost:3306/daas
    locations: classpath:db/migration
    driver-class-name: com.mysql.jdbc.Driver
