spring:
  datasource:
    url: jdbc:mysql://localhost:3306/daas
    username: "daas"
    password: "daas"

  flyway:
    password: "daas"
    user: "daas"
    url: jdbc:mysql://localhost:3306/daas
    locations: classpath:db/migration
