package dev.abelab.daas.db.mapper;

import dev.abelab.daas.db.entity.Dajare;
import dev.abelab.daas.db.entity.DajareExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface DajareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dajare
     *
     * @mbg.generated Sun May 16 17:18:20 JST 2021
     */
    long countByExample(DajareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dajare
     *
     * @mbg.generated Sun May 16 17:18:20 JST 2021
     */
    int deleteByExample(DajareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dajare
     *
     * @mbg.generated Sun May 16 17:18:20 JST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dajare
     *
     * @mbg.generated Sun May 16 17:18:20 JST 2021
     */
    int insert(Dajare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dajare
     *
     * @mbg.generated Sun May 16 17:18:20 JST 2021
     */
    int insertSelective(Dajare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dajare
     *
     * @mbg.generated Sun May 16 17:18:20 JST 2021
     */
    List<Dajare> selectByExample(DajareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dajare
     *
     * @mbg.generated Sun May 16 17:18:20 JST 2021
     */
    Dajare selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dajare
     *
     * @mbg.generated Sun May 16 17:18:20 JST 2021
     */
    int updateByExampleSelective(@Param("record") Dajare record, @Param("example") DajareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dajare
     *
     * @mbg.generated Sun May 16 17:18:20 JST 2021
     */
    int updateByExample(@Param("record") Dajare record, @Param("example") DajareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dajare
     *
     * @mbg.generated Sun May 16 17:18:20 JST 2021
     */
    int updateByPrimaryKeySelective(Dajare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dajare
     *
     * @mbg.generated Sun May 16 17:18:20 JST 2021
     */
    int updateByPrimaryKey(Dajare record);
}